### ISSUE TITLE
Ignition 7.9 - Tag real-time override cannot be changed on a per-tag basis

### ISSUE THREAD

**Issue by alexjhawk** [hms-networks/IgnitionEwonConnector#107]
A tag real-time override cannot be performed on a per-tag basis in Ignition 7.9 to allow individual tags to be read in realtime.

**Comment by alexjhawk** [comment]
Due to a limitation in the available tag provider in Ignition 7.9, a real-time override flag cannot be added at a per-tag level. This functionality in Ignition 7.9 is limited to the following real-time overrides: all tags, per-Ewon.

**Comment by it-hms** [comment]
This issue is closed as fix not possible.
