### ISSUE TITLE
Time Zones and Historical Data

### ISSUE THREAD

**Issue by MaxHanson** [hms-networks/IgnitionEwonConnector#149]
Does the connector account for the Flexy local time zone for Flexy historical data? Or is it necessary to select the "Record data in UTC" option in the Flexy Setup>System>General>Date & Time configuration?

**Comment by alexjhawk** [comment]
Hi @MaxHanson,

The Ignition Ewon Connector uses Ewon's DataMailbox API for historical data, which accounts for Flexy's local time zone configuration. The image below shows the time behavior when the 'Record data in UTC' option is checked or unchecked:

![image](https://github.com/hms-networks/IgnitionEwonConnector/assets/51409174/eafba049-0bfe-4946-9907-42b2021bedf5)

As shown, tag history, alarm states, and alarm history will use the local time stamp unless the 'Record data in UTC' option is selected. 

Additional details of the time zone behaviors of the DataMailbox API can be found in the [UTC Timestamp Logging Solution Sheet](https://hmsnetworks.blob.core.windows.net/www/docs/librariesprovider10/downloads-monitored/manuals/knowledge-base/kb-0284-01-en-utc-timestamp-logging.pdf) document.

Please let me know if you have any additional questions, and feel free to close this issue if I've been able to answer your question.

Best regards,

@alexjhawk
