### ISSUE TITLE
Different code quality into IGN Tag Historian than DM one

### ISSUE THREAD

**Issue by gomez100** [hms-networks/IgnitionEwonConnector#154]
Hi, 
it seems the datas/points pushed into Ignition TagHistorian after a sync from DM performed by HMS module, do not provide the correct Quality. I.e. if from Ewon a tag is pushed to DM with good quality value ( 3 ) ( it's a memory tag ) it's stored into IGN historian with Quality = 0. It prevent some objects to work properly, i.e. Easy Chart.

**Comment by jakef4** [comment]
I am also experiencing this issue.

Is there any plans for this to be resolved?

**Comment by it-hms** [comment]
This issue will be address in the next release

**Comment by jakef4** [comment]
Hi Ian,

Is there any kind of timeline for the next release?

Just curious if the time frame is like a week, or multiple moths away.

Thanks

**Comment by it-hms** [comment]
@jakef4, 
I have made the PR with the changes. But this still needs to be tested and reviewed. Should be ready in another couple weeks - I have not scheduled time with our tester so that is the reason for the delay.
