### ISSUE TITLE
Boolean tag data type can not change value

### ISSUE THREAD

**Issue by tedsch** [hms-networks/IgnitionEwonConnector#155]
With V2.0 and Ignition 8.1 can not change the value of a boolean tag.  Setup a string, int and boolean memory tag on a Flexy unit.  Was able to change the value of the string and int tags but not the boolean tag.

V1.2 and Ignition 8.1 you can change the value of a boolean data type tag.

**Comment by it-hms** [comment]
I think we understand why this is happening. 

https://github.com/hms-networks/IgnitionEwonConnector/blob/6028073ff29a50896caaf954a0e2eb65d72a1056/eWonConnector-gateway/src/main/java/com/hms_networks/americas/sc/ignition/comm/requests/m2w/M2WebEwonUpdateTagValuesRequest.java#L118

The following will append `true` or `false` for Boolean objects, but the Flexy UpdateTagForm handles `1` or `0`. 

When we make the next release, we will pull in this issue.
