### ISSUE TITLE
Allow for Individual eWONs to switch to all realtime values at runtime

### ISSUE THREAD

**Issue by TomKimsey** [hms-networks/IgnitionEwonConnector#22]

**Comment by TomKimsey** [comment]
@alexjhawk here is a commit that adds a tag in ignition for each ewon under the _config directory 

79cf4f28203f0cde2d3388711f2382a45f486ec8

**Comment by alexjhawk** [comment]
Is that commit only partial functionality? or what is the status of this? (since there is already a commit)

**Comment by TomKimsey** [comment]
It only adds the tags to Ignition, if you build and run off that commit you will see under each ewon a folder called _config, and under that a boolean tag.  None of the other functionality is there.

**Comment by alexjhawk** [comment]
Ok, thanks

**Comment by TomKimsey** [comment]
In updateLive() there is a HashMap that contains names of ewons tied to an array list of the tags that should be read live.  Before the tags are checked for the realtime parameter being true you would want to run through each ewon and check if the _config/AllRealtime value is true.  If it is then when each tag is checked for its own realtime value if that ewon specifies allrealtime then that tag should get added to the arraylist stored in the hashmap for that ewon regardless of its own realtime value.  

There is probably a good amount of optimization that could be done in the updateLive method if you are ambitious but it should be quick to add this functionality.
